# This is a sample to deploy a milvus cluster with minimum cost of resources.
# It should be used for testing and development purposes only.
# Total resources required is about: 0.1 CPU, 100 MiB memory
# When deleted, all the data in the Milvus will be lost.

apiVersion: milvus.io/v1beta1
kind: Milvus
metadata:
  name: my-release
  labels:
    app: milvus
spec:
  config: {}
  components:
    standalone:
      replicas: 1
      serviceType: ClusterIP
  dependencies:
    etcd:
      inCluster:
        values:
          replicaCount: 1
        deletionPolicy: Delete
        pvcDeletion: true
    storage:
      inCluster:
        values:
          mode: standalone
          resources:
            requests:
              memory: 100Mi
          persistence:
              size: 20Gi
        deletionPolicy: Delete
        pvcDeletion: true
 